$schema: "http://json-schema.org/draft-07/schema#"
description: entries for the sample sheet
properties:
  sample:
    type: string
    description: sample name/identifier
  lane_number:
    type: integer
    description: number of the lane that files originate from. If multiple lanes per sample exist, please provide one sample sheet line per lane, with a read1 and read2 entry each. Will default to a dummy value of "1", if none is provided in the sample sheet.
  library_type:
    type: string
    description: 'Defaults to "Gene Expression" if none is provided in the sample sheet. Otherwise, specify one of the 10X genomics library types, either "Gene Expression" or one of those listed here: https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/inputs/cr-libraries-csv#library-types'
  read1:
    type: string
    description: path and name of fastq.gz files, read 1
  read2:
    type: string
    description: path and name of fastq.gz files, read 2 (optional)

required:
  - sample
  - read1
  - read2
